### ISSUE TITLE
moby_runtime configuration in the /etc/iotedge/config.yaml does not take any effect while running iotEdge

### ISSUE THREAD

**Issue by kharsha345** [Azure/azure-iot-sdk-c#1892]
I am trying to change the IP configuration of IoT Edge, as it is running in Loop Back address by default. I am able to run Edge and Edge Hub successfully and ran the iotedge_downstream_device_sample.c example. Now the issue is i am using a certain hardware which uses Wifi as connectivity, so i need to change the Edge IP configuration. Suggest ho should i do it?

I have tried changing the configuration in config.yaml file which does not take any effect.

Also another question is should i use iotedge (v 1.1 or 1.0) or should i use aziot-edge (v 1.2) for connecting a downstream device to IoT Edge gateway?

Changes made:
```
moby_runtime:
  uri: "unix:///var/run/docker.sock"
  network:
    name: "azure-iot-edge"
    ipv6: false
    ipam:
      config:
        -
            gateway: '192.168.0.1/24'
            subnet: '192.168.0.0/24'
            ip_range: '192.168.0.104/40'
        -
            gateway: '2021:ffff:e0:3b1:1::1'
            subnet: '2021:ffff:e0:3b1:1::/80'
            ip_range: '2021:ffff:e0:3b1:1::/80'
```

Things tried:
1. I have tried changing the host name, by directly giving IP address, that didn't work.
2. I have followed some steps to check on the Docker container details, which gives the EdgeAgent ip 172.18.0.3 and EdgeHub ip 172.18.0.2. <IP never changes>

Below are the System address
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:ae:ed:38:c8:d5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.104/24 brd 192.168.0.255 scope global dynamic enp2s0
       valid_lft 81456sec preferred_lft 81456sec
    inet6 fe80::a8ec:ce31:9604:7b01/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:cd:1c:52:87 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:cdff:fe1c:5287/64 scope link 
       valid_lft forever preferred_lft forever
4: br-27fe154011e8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:39:98:6d:0c brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-27fe154011e8
       valid_lft forever preferred_lft forever
    inet6 fe80::42:39ff:fe98:6d0c/64 scope link 
       valid_lft forever preferred_lft forever
86: veth8cc82d7@if85: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-27fe154011e8 state UP group default 
    link/ether 82:84:0e:cb:66:fe brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::8084:eff:fecb:66fe/64 scope link 
       valid_lft forever preferred_lft forever
88: veth62d6b85@if87: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-27fe154011e8 state UP group default 
    link/ether c6:04:28:ee:de:52 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::c404:28ff:feee:de52/64 scope link 
       valid_lft forever preferred_lft forever
```
Neither did docker changes the IP.

Help me with this
Thanks.
